services:
  postgres:
    image: postgres:13
    container_name: dev-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # trunk-ignore(yamllint/quoted-strings)
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  reviews-service:
    build:
      context: ./backend
    container_name: reviews_service
    # restart: always
    env_file:
      - ./backend/.env.dev
    depends_on:
      - postgres
    ports:
      # trunk-ignore(yamllint/quoted-strings)
      - "8080:8080"

volumes:
  postgres_data:
